
DATA_RAW = "data/raw"
DATA_PROCESSED = "data/processed"

DATA_RAW_CASES = f"{DATA_RAW}/cases"
DATA_RAW_STATUTES = f"{DATA_RAW}/statutes"
DATA_RAW_GAZETTES = f"{DATA_RAW}/gazettes"

DATA_PROCESSED_CASES = f"{DATA_PROCESSED}/cases"
DATA_PROCESSED_STATUTES = f"{DATA_PROCESSED}/statutes"
DATA_PROCESSED_GAZETTES = f"{DATA_PROCESSED}/gazettes"
